require 'rake'

task :default => [:rebuild_and_run]

task :cmake do
  desc "Runs the cmake command"
  Dir.mkdir "build" if !File.exists? "build"
  puts `cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ./`
end

task :make do
  desc "Runs the make command after cmake is run"
  make
end

task :clean do
  desc "Cleans previous build"
  `rm Makefile`
  `rm euler`
end

task :build do
  desc "Builds everything"
  Rake::Task["cmake"].execute
  Rake::Task["make"].execute
end

task :rebuild do
  desc "Rebuilds everything"
  Rake::Task["clean"].execute
  Rake::Task["cmake"].execute
  Rake::Task["make"].execute
end

task :run do
  STDOUT.sync = true
  puts `./euler`
end

task :rebuild_and_run do
  desc "Rebuilds everything and runs the executable"
  Rake::Task["rebuild"].execute
  Rake::Task["run"].execute
end

def cmake
  puts "calling the cmake command"
  puts `cmake .`
end

def make
  puts "calling the make command"
  puts `make`
end
